export const PRODUCTS = [
  {
    id: "6a2d29efa993b7307f224524",
    category: "WORKOUTS",
    title: ["THE TRAINING", "PROTOCOL"],
    features: ["MUSCLE WHERE IT'S SEEN", "A SPLIT BUILT FOR YOU", "PROOF YOU'RE PROGRESSING"],
    duration: "LIFETIME ACCESS",
    image: "/images/training.png",
    subtitle: "BUILD THE PHYSIQUE",
    price: 999,
    originalPrice: 1899,
  },
  {
    id: "6a2d29efa993b7307f224525",
    category: "NUTRITION",
    title: ["DIET", "PROTOCOL"],
    subtitle: "EAT LIKE IT'S HANDLED",
    features: ["LEAN OUT, NO TRACKING", "NEW MEALS, ZERO THINKING", "VEG & NON-VEG COVERED"],
    duration: "LIFETIME ACCESS",
    image: "/images/diet.png",
    price: 699,
    originalPrice: 1799,
  },
  {
    id: "6a2d29efa993b7307f224526",
    category: "AESTHETICS",
    title: ["SKIN", "PROTOCOL"],
    features: ["CLEAR ACNE & TEXTURE", "LOOK AWAKE, NOT TIRED", "ZERO GUESSWORK SHOPPING"],
    duration: "LIFETIME ACCESS",
    subtitle: "CLEAR SKIN, FAST",
    image: "/images/skin.png",
    price: 499,
    originalPrice: 1299,
  },
  {
    id: "6a2d29efa993b7307f224527",
    category: "AESTHETICS",
    title: ["FRAME", "PROTOCOL"],
    features: ["SHARPER JAWLINES & CHEEKBONES", "DROP FACIAL FAT FAST", "DE-BLOAT IN 48 HOURS"],
    duration: "LIFETIME ACCESS",
    subtitle: "FACIAL AESTHETICS",
    image: "/images/frame.png",
    price: 399,
    originalPrice: 999,
  },
]

export const MAIN_PACKAGE = {
  id: "6a2d29efa993b7307f224528",
  badge: "LIMITED OFFER",
  label: "LEVEL UP",
  title: ["THE MOGWARD", "PROTOCOL"],
  description: "Full access to everything. Peak performance guaranteed.",
  features: ["PHYSIQUE THAT TURNS HEADS", "FOOD THAT BUILDS THE BODY", "GLASS SKIN", "THE FACE THAT PEOPLE NOTICE"],
  price: 1999,
  originalPrice: 2599,
  duration: "LIFETIME ACCESS",
  perMonth: "FREE",
  image: "/images/combo.png",
}