export const PRODUCTS = [
  {
    id: "6a2d29efa993b7307f224524",
    category: "WORKOUTS",
    title: ["THE TRAINING", "PROTOCOL"],
    features: ["MUSCLE WHERE IT'S SEEN", "A SPLIT BUILT FOR YOU", "PROOF YOU'RE PROGRESSING"],
    duration: "LIFETIME ACCESS",
    image: "/images/training.png",
    subtitle: "BUILD THE PHYSIQUE",
    price: 999,
    originalPrice: 1899,
    discount: "45% off",
    description: {
      framework: "THE FRAMEWORK",
      hook: "THE SCIENCE OF HOW MUSCLE ACTUALLY GROWS",
      body: "Most \"programs\" are just exercise lists. This is the actual mechanism — tension, volume, recovery — translated into a system that tells you exactly what to do, how hard, and when to push.",
      included: [
        "Muscle-by-muscle volume & frequency targets",
        "How close to failure you actually need to train",
        "How to know when (and how) to progress",
        "My current complete workout split + 1 Extra!",
      ],
      whoFor: "Anyone stuck on the same program for a year with nothing to show for it. This tells you exactly what's missing — and fixes it without 2-hour gym sessions.",
    },
  },
  {
    id: "6a2d29efa993b7307f224525",
    category: "NUTRITION",
    title: ["DIET", "PROTOCOL"],
    subtitle: "EAT LIKE IT'S HANDLED",
    features: ["LEAN OUT, NO TRACKING", "NEW MEALS, ZERO THINKING", "VEG & NON-VEG COVERED"],
    duration: "LIFETIME ACCESS",
    image: "/images/diet.png",
    price: 699,
    originalPrice: 1799,
    discount: "60% off",
    description: {
      framework: "THE FRAMEWORK",
      hook: "TWO NUMBERS. THAT'S THE WHOLE DIET.",
      body: "Calories and protein — everything else (meal timing, intermittent fasting, \"clean eating\") is decoration. This system shows you how to find your real maintenance in one week, then run a deficit without losing the muscle you've built.",
      included: [
        "The 1-week protocol to find your true maintenance",
        "Exact protein targets — no guessing",
        "Why a deficit doesn't have to cost you muscle",
        "What to actually eat — flexible, not restrictive",
      ],
      whoFor: "Anyone who's \"tried everything\" and stayed the same weight. If you've never actually tracked your real numbers, this is the first thing that will work.",
    },
  },
  {
    id: "6a2d29efa993b7307f224526",
    category: "AESTHETICS",
    title: ["SKIN", "PROTOCOL"],
    features: ["CLEAR ACNE & TEXTURE", "LOOK AWAKE, NOT TIRED", "ZERO GUESSWORK SHOPPING"],
    duration: "LIFETIME ACCESS",
    subtitle: "CLEAR SKIN, FAST",
    image: "/images/skin.png",
    price: 499,
    originalPrice: 1299,
    discount: "60% off",
    description: {
      framework: "THE FRAMEWORK",
      hook: "CLEANSE. TREAT. PROTECT.",
      body: "No 10-step routines, no guessing which $60 serum actually does anything. Three steps, in order, cover 99% of what skin actually needs — and we show you exactly which ingredients (not products) solve your specific concern.",
      included: [
        "The full CTP system, step by step",
        "Concern-to-ingredient map (acne, pigmentation, aging, redness)",
        "How to read any product label in 10 seconds",
        "The retinoid + SPF non-negotiables, done right",
      ],
      whoFor: "Anyone tired of buying products that do nothing. If you've got an actual concern — breakouts, dullness, uneven tone — this tells you the exact ingredient that fixes it, not a 12-step ritual to maintain.",
    },
  },
  {
    id: "6a2d29efa993b7307f224527",
    category: "AESTHETICS",
    title: ["FRAME", "PROTOCOL"],
    features: ["SHARPER JAWLINES & CHEEKBONES", "DROP FACIAL FAT FAST", "DE-BLOAT IN 48 HOURS"],
    duration: "LIFETIME ACCESS",
    subtitle: "FACIAL AESTHETICS",
    image: "/images/frame.png",
    price: 399,
    originalPrice: 999,
    discount: "60% off" ,
    description: {
      framework: "THE FRAMEWORK",
      hook: "5 STEPS, IN ORDER — NOT A LIST OF TIPS",
      body: "Step 1 (fat loss) does 80% of the visible work. Skip the order and you're polishing a jawline that's still hidden under fat. This system tells you exactly what to do first, second, and last — and why doing it out of order wastes months.",
      included: [
        "The exact 5-step hierarchy (fat loss → mewing → de-bloat → nose breathing → skin)",
        "Body fat % targets mapped to visible jaw/cheekbone definition",
        "The 48-hour de-bloat protocol",
        "Sleep mewing + mouth taping, done safely",
      ],
      whoFor: "Anyone who's tried mewing or \"looksmaxxing\" tips with no real change. This explains why those tips don't work in isolation — and what order actually moves your face.",
    },
  },
]

export const MAIN_PACKAGE = {
  id: "6a2d29efa993b7307f224528",
  badge: "LIMITED OFFER",
  label: "LEVEL UP",
  summary: "FOUR PROTOCOLS. ONE TRANSFORMATION.",
  title: ["THE MOGWARD", "PROTOCOL"],
  description: {
    framework: "THE FRAMEWORK",
    hook: "ONE SYSTEM, NOT FOUR SEPARATE ONES",
    body: "Your face, your body, your skin, and your physique aren't separate projects — they run on the same two inputs: body composition and consistency. Train, Diet, Frame, and Skin are built to compound off each other, not sit in isolation.",
    included: [
      "Training Protocol — the full hypertrophy system",
      "Diet Protocol — calories & protein, dialed in",
      "Frame Protocol — the 5-step facial hierarchy",
      "Skin Protocol — CTP, done right",
      "Every cross-system reference, already mapped for you",
    ],
    bonusTitle: "BUNDLE-ONLY BONUS: SUPPORT+",
    bonusBody: "Buy the bundle and you're not just another follower in the DMs. I personally keep bundle members in my priority inbox — your questions get seen and answered first, not buried under everyone else's.",
    whyTitle: "WHY THE BUNDLE BEATS BUYING SOLO",
    whyBody: "Frame Protocol's Step 1 is Diet Protocol's entire job. Training Protocol's results show up faster with Diet Protocol running underneath it. Buy them separately and you're piecing together a system we already built whole — for less than the individual prices combined.",
    whoFor: "Anyone serious enough to stop fixing one thing at a time. If you actually want the full transformation — not just better skin, or just a bigger lift — this is the complete version of everything else on this page.",
  },
  features: ["PHYSIQUE THAT TURNS HEADS", "FOOD THAT BUILDS THE BODY", "GLASS SKIN", "THE FACE THAT PEOPLE NOTICE"],
  price: 1999,
  originalPrice: 5999,
  duration: "LIFETIME ACCESS",
  perMonth: "FREE",
  image: "/images/combo.png",
  discount: "67% off"
}