export const PRODUCTS = [
  {
    id: "6a2d29efa993b7307f224524",
    category: "WORKOUTS",
    title: ["THE TRAINING", "PROTOCOL"],
    features: ["MY WORKOUT SPLIT", "WORKOUT LOGGER", "PERFORMANCE ANALYTICS"],
    duration: "LIFETIME ACCESS",
    image: "/images/training.png",
    subtitle: "FITNESS TRANSFORMATION",
    price: 999,
    originalPrice: 1800,
  },
  {
    id: "6a2d29efa993b7307f224525",
    category: "NUTRITION",
    title: ["DIET", "PROTOCOL"],
    subtitle: "SUMMER EDITION",
    features: ["6 NEW MEALS EVERYDAY", "VEG/NON-VEG", "EASY TO FOLLOW RECIPES", "MACROS BREAKDOWN"],
    duration: "LIFETIME ACCESS",
    image: "/images/diet.png",
    price: 699,
    originalPrice: 1799,
  },
  {
    id: "6a2d29efa993b7307f224526",
    category: "AESTHETICS",
    title: ["SKIN", "PROTOCOL"],
    features: ["SKIN TYPE DIAGNOSTICS", "AM/PM ROUTINE", "PRODUCTS GUIDE", "MISTAKES TO AVOID"],
    duration: "LIFETIME ACCESS",
    subtitle: "SKIN CARE MASTERY",
    image: "/images/skin.png",
    price: 499,
    originalPrice: 1299,
  },
  {
    id: "6a2d29efa993b7307f224527",
    category: "AESTHETICS",
    title: ["FRAME", "PROTOCOL"],
    features: ["SKIN TYPE DIAGNOSTICS", "PRODUCTS GUIDE", "MISTAKES TO AVOID"],
    duration: "LIFETIME ACCESS",
    subtitle: "SKIN CARE MASTERY",
    image: "/images/frame.png",
    price: 399,
    originalPrice: 999,
  },
]

export const MAIN_PACKAGE = {
  id: "6a2d29efa993b7307f224528",
  badge: "LIMITED OFFER",
  label: "LEVEL UP",
  title: ["THE MOGWARD", "PROTOCOL"],
  description: "Full access to everything. Peak performance guaranteed.",
  features: ["THE SUMMER SPLIT", "MUSCLE KITCHEN", "SKIN CARE", "HAIR CARE"],
  price: 1999,
  originalPrice: 4999,
  duration: "LIFETIME ACCESS",
  perMonth: "FREE",
  image: "/images/combo.png",
}